site_name: EventList for Joomla 4
site_url: https://ulricusr.github.io/joomla4-eventlist
repo_url: https://github.com/UlricusR/joomla4-eventlist
edit_uri: edit/site-sources/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font: false # To avoid utilization of Google fonts
  logo: assets/images/logo_white_small.png
  favicon: assets/images/favicon.png

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UlricusR
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ulrichrueth/

plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          site_name: EventList for Joomla 4
          homepage: https://ulricusr.github.io/en
        de:
          name: Deutsch
          site_name: EventList für Joomla 4
          homepage: https://ulricusr.github.io/de
  - search
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
