# Project information
site_name: EventList for Joomla 4
site_url: https://www.rueth.info/joomla4-eventlist
site_author: Ulrich Rüth
site_description: >-
  A Joomla! package for displaying a list of weekly recurring events
edit_uri: edit/site-sources/docs/

# Repository
repo_name: UlricusR/joomla4-eventlist
repo_url: https://github.com/UlricusR/joomla4-eventlist

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font: false # To avoid utilization of Google fonts
  logo: assets/images/logo_white_small.png
  favicon: assets/images/favicon.png

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UlricusR
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ulrichrueth/

# Page tree
nav:
  - Project Overview: https://www.rueth.info
  - EasyFPU for iOS: https://www.rueth.info/iOS-EasyFPU/
  - EasyFPU for Android: https://www.rueth.info/Android-EasyFPU/
  - EventList for Joomla:
    - 'What is EventList for Joomla?': 'index.md'
    - 'Installation': 'installation.md'
    - 'Configuration': 'configuration.md'
    - 'Usage': 'usage.md'
  - ChurchCal for Joomla: https://www.rueth.info/joomla-churchcal/
  - Legal Notice: https://www.rueth.info/legal/


# Plugins
plugins:
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: de
          name: Deutsch
          build: true
          site_name: EventList für Joomla 4
          site_description: >-
            Ein Joomla!-Paket zum Anzeigen von regelmäßigen Veranstaltungen
          site_url: https://www.rueth.info/joomla4-eventlist/de
          nav_translations:
            # Tab Menu
            Project Overview: Projektübersicht
            EasyFPU for iOS: EasyFPE für iOS
            EasyFPU for Android: EasyFPE für Android
            EventList for Joomla: EventList für Joomla
            ChurchCal for Joomla: ChurchCal für Joomla
            Legal Notice: Impressum und Datenschutz
            # Page Menu
            What is EventList for Joomla?: Was ist EventList für Joomla?
            Installation: Installation
            Configuration: Konfiguration
            Usage: Nutzung
          nav:
            - Projektübersicht: https://www.rueth.info/de
            - EasyFPE für iOS: https://www.rueth.info/iOS-EasyFPU/de/
            - EasyFPE für Android: https://www.rueth.info/Android-EasyFPU/de/
            - EventList für Joomla:
              - 'Was ist EventList für Joomla?': 'index.md'
              - 'Installation': 'installation.md'
              - 'Konfiguration': 'configuration.md'
              - 'Nutzung': 'usage.md'
            - ChurchCal für Joomla: https://www.rueth.info/joomla-churchcal/de/
            - Impressum und Datenschutz: https://www.rueth.info/de/legal/
  - search
  - glightbox

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
